### ISSUE TITLE
Using term "Primary" for custom input seed color is misleading

### ISSUE THREAD

**Issue by sergejsha** [material-foundation/material-theme-builder#209] opened 2023-08-24 09:41 UTC
**Describe the bug**
Using term "Primary" for custom input seed color is extremely misleading

**To Reproduce**
1. Open https://m3.material.io/theme-builder#/custom
2. Set "Primary (Acts as custom source color)" to a color of your choice
3. Check generated Light Scheme.
4. Both the custom source color and the primary color in the scheme are called "Primary" but have different values. At the same time Secondary and Tertiary colors under "Core colors" and in generated schemes match, which is inconsistent to Primary colors.

Note: https://material.io/blog/science-of-color-design and https://material.io/blog/dynamic-color-harmony were read through.

**Expected behavior**
Builder makes it clear that exact Primary color for the scheme cannot be chosen, but a custom source color for the Primary color can be given. This should be clear even without reading blog posts linked under the note above. Ideally, the term "Primary" should only be used for colors in generated schemes.

**Screenshots**
<img width="400" alt="Screenshot 2023-08-24 at 11 03 42" src="https://github.com/material-foundation/material-theme-builder/assets/768721/d3798a2c-ca0e-43bc-838e-4e1a33168010">

**Comment by ale7780s** [comment] 2023-09-08 14:40
"The color system automatically handles critical adjustments that provide accessible color contrast". The way I interpret this is that when you select a custom Primary colour, the Hue is extracted and then Chroma and Tone are adjusted to provide you with the set of shades you need for the interface.

I don't disagree with you, the tool is not very straightforward.

**Comment by danielwilson1702** [comment] 2023-09-12 18:12
There must be other issues on this no? I find this tool extremely stupid for most use cases. If I have a brand color of #2DCCD3 that I have to use, and set it as the primary color, then why in the name of god are none of the compose tokens using that hex value.

Furthermore [this image](https://m3.material.io/styles/color/the-color-system/color-roles) is a complete lie:
![image](https://github.com/material-foundation/material-theme-builder/assets/5859421/c8115f1b-987c-44bf-b637-f63fc3b65258)

Like the generator sounds like it should do this, keeping the key colors and generating colors around them, and that would make sense. But it just doesn't. Was there two different departments involved in this? Where the guys who built the generator just decided it would be nice to magic up some rando colors? Do people actually find this useful?

**Comment by danielwilson1702** [comment] 2023-09-12 18:19
Ok we have https://github.com/material-foundation/material-theme-builder/issues/150 as a dupe of this (and the OG issue https://github.com/material-foundation/material-theme-builder/issues/8).

This tool was a massive waste of time guys sorry, we'll just do it by hand and see what it looks like

**Comment by margeeta** [comment] 2023-09-12 18:36
The Material Theme Builder uses Material Color Utilities for the generation algorithm, which helps create full schemes from limited inputs and mimic how dynamic color works for Android. 
The hue is used while the chroma and tone are adjusted to create the key colors, and the tonal indices are then created. 
The primary color role is tone 40 of the Primary tonal palette.
This is explained in more detailed here: https://developer.android.com/design/ui/mobile/guides/styles/color#color-system-process
![image](https://github.com/material-foundation/material-theme-builder/assets/10263978/d3a93e16-847d-47d3-9073-971d4885b179)
![image](https://github.com/material-foundation/material-theme-builder/assets/10263978/ad3b72e3-eba5-4b7d-8fbc-3befa896890b)
Inputting a color, revealing the HCT values. While the hue persists, the input color has a tone of 86, so it will be close to the Primary Container input, but not Primary.

The Figma version can also be used for more manual or granular adjustments by editing the Figma style properties, they will export. Or of course, once you get a theme that is close, export the theme file and update the hex values in color.kt/color.xml.

**Comment by danielwilson1702** [comment] 2023-09-12 22:39
Ok this makes a lot more sense now thank you. I don't think this is linked anywhere in the Color section on https://m3.material.io/ by the way and is _much_ more informative. 

So it creates a tonal palette from the input color and using a load of theory has decided that number 40 on the palette will always be the primary color, number 100 will always be the on-primary color etc.

This is fundamentally only suitable for generating color schemes from images if you can't by-design "lock in" brand colors and have this HCT system generate appropriate colors from those.

In the example `#b5e0ef` is close to P-90, therefore not only does it decide for itself that 40 is a "nicer" color, it doesn't even shift the closest tone assignment of P-90 down to equal `#b5e0ef`. In other words, it takes your primary color and says "I don't like that try these ones instead".

Obviously no one is going to change how this works because I disagree with that and I'm sure you have adoption metrics that have decided the millions of dollars here were well spent :) 

I would recommend to avoid the confusion here adding a link to https://developer.android.com/design/ui/mobile/guides/styles/color#using-material on the m3 site, and to consider relabelling the core colors: 
![Untitled](https://github.com/material-foundation/material-theme-builder/assets/5859421/f55b98b6-690c-48ff-9478-bde4a4420440)

**Closed** 2024-01-19 02:08 UTC
