### ISSUE TITLE
Opacity styles don't switch between day and night themes

### ISSUE THREAD

**Issue by PrattiDev** [material-foundation/material-theme-builder#62] opened 2022-04-24 11:02 UTC
**Describe the bug**
While all other styles switch to their /dark/ counterparts as expected, the opacity styles — used for state management in components — do not.

**To Reproduce**
1. Get any component with an opacity style applied to it.
2. Open the Material Theme Builder plugin.
3. Click on the moon icon to switch themes.
4. The opacity style will not update alongside all the others.

**Expected behavior**
The style is supposed to swap to its dark counterpart so users can quickly switch themes without hunting down instances of opacity styles to manually switch.

**Screenshots**

Here is a FAB in a pressed state. It contains an opacity layer, corresponding with the Material You guidelines. Its pressed state overlay does not switch accordingly.

<img width="632" alt="bug_report" src="https://user-images.githubusercontent.com/17130024/164973170-67ae1360-d409-4ebc-93f2-5ed880c85d58.png">

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome (Stable), Figma app (Stable)

**Comment by pbutterworth** [comment] 2022-04-29 03:04
Similar/duplicate of #59

**Closed** 2022-06-29 01:39 UTC
Labels: figma
